### ISSUE TITLE
Usage help

### ISSUE THREAD

**Issue by tomkwok** [DevinR528/luge#1]
This tool gives an error when used with database created with the latest version of Conduit.

```
What you looking for: rooms
Rooms for server: localhost
What you looking for: pdus localhost
Error: MissingLeadingSigil
```

```
What you looking for: rooms
Rooms for server: localhost
What you looking for: all localhost
Error: MissingLeadingSigil
```

**Comment by DevinR528** [comment]
Ah so that error message is terrible, I should probably do something about that. When you use the `all` or `pdus` command it wants a RoomId so `#roomname:server.com`.

Unfortunately, the `rooms` command will not be very helpful because it only prints public rooms which I don't think conduit handles currently. The output from that should look
```
Rooms for server: localhost
#room:server.com
#room2:server.com
#room3:server.com
```
but won't until public rooms are handled.

So an example command may look like `all #conduit:matrix.org` which would print all the events in the DB for that room or `pdus #conduit:matrix.org` that would print all the current state events. A third argument can be passed to filter the resulting JSON strings `pdus #conduit:matrix.org power` would give pdus that contain the word power (so power events and such).

**Comment by tomkwok** [comment]
Thanks, I am able to inspect a database following your examples. However, if I try to inspect the database of a working conduit instance, it shows that the database is locked. Is it possible to make live inspection work, or is it necessary to either shut down the server or make a copy of the database folder to inspect it?

**Comment by DevinR528** [comment]
Yeah, I've thought that would be pretty damn useful too unfortunately sled will error if the db file is in use somewhere else. Sadly there is no way around this.
